version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:v1.0.1
    restart: on-failure
    environment:
      APP_HOST: anthonybauld-aggr_aggr_1
      APP_PORT: 8080

  aggr:
    image: ghcr.io/anthonybauld/aggr:latest
    restart: on-failure
    environment:
      - PORT=8080
