version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:v1.0.0
    restart: on-failure
    ports:
      - "8080:80"
    environment:
      APP_HOST: web
      APP_PORT: 80

  web:
    image: tucsky/aggr-server:latest
    restart: on-failure
    environment:
      - PORT=80
